# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    keywords: miccall
    backgroundpic : "img/bg.jpg"

Intro:
    name: Screamer Alliance WFC
    slogan: "欢迎每一位热爱足球的女性"
    HeadButton: Screamer Alliance WFC

Nav:
    Home_name: 主页
    is_use_categories : true 
    categories_name: 分类
    is_use_archives : false
    archives_name: 归档
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github:
            use: false # 是否启用
            link: # 点击地址
        Twitter:
            use: false
            link:
        Facebook:
            use: false
            link:
        Instagram: #没有ig的icon，找不到icon文件的位置
            use: true
            link: https://www.instagram.com/screameralliancewfc/

    pages: #自定义连接页
    # link 的参数为相对路径，对应 hexo 目录下的 source 件夹内的相应文件夹


        About us: 
            link: "/about_us/"
        Join us :
            link: "/join_us/"
        Support & Wellbeing :
            link: "/support_wellbeing/"

        标签:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”



MainFirst: #导航栏下面的主页
    name: Miccall Metro #大标题名字
    description: Technical  Artist  of  Games   #第二标签 描述
    pic_url: /images/me.jpg #图片地址
    goto_ulr: ""

Gallery :
    title: Mr.metro 
    description: Just another fine responsive 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: false
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML